#!/usr/bin/env python3
"""Regenerates test/kotoba/kir/host_eval_ops.txt (every operation head the host
`kotoba.kir/eval-expr` dispatches on: the `(= op 'x)` / `(contains? '#{..} op)`
arms plus test/kotoba/kir/kernel_operations.txt) and the `host-op-group-N?`
functions inside src/kotoba/kir/interp.cljk between the GENERATED markers.
usage: tools/gen_host_ops.py [kir.cljk]"""
import re, sys, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
kir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, 'src/kotoba/kir.cljk')
lines = open(kir).read().split('\n')
start = next(i for i, l in enumerate(lines) if l.startswith('(defn eval-expr'))
end = next(i for i, l in enumerate(lines) if l.startswith('(defn execute'))
txt = '\n'.join(lines[start:end])
names = set()
for m in re.finditer(r"\(= op '([^\s)]+)\)", txt): names.add(m.group(1))
for m in re.finditer(r"\(contains\? '#\{([^}]*)\} op\)", txt): names.update(m.group(1).split())
names.update(x.strip() for x in open(os.path.join(root, 'test/kotoba/kir/kernel_operations.txt')) if x.strip())
names.add('bytes-literal-length')
names = sorted(names)
open(os.path.join(root, 'test/kotoba/kir/host_eval_ops.txt'), 'w').write('\n'.join(names) + '\n')
groups = [names[i:i + 16] for i in range(0, len(names), 16)]
out = []
for gi, g in enumerate(groups):
    out.append('(defn- host-op-group-%d? [s :string] :bool\n  (or %s))\n' % (gi, ' '.join('(string=? s "%s")' % n for n in g)))
out.append('(defn host-op-name? [s :string] :bool\n  (or %s))\n' % ' '.join('(host-op-group-%d? s)' % i for i in range(len(groups))))
gen = ';; GENERATED by tools/gen_host_ops.py -- do not edit by hand\n' + '\n'.join(out) + ';; END GENERATED\n'
src = os.path.join(root, 'src/kotoba/kir/interp.cljk')
t = open(src).read()
t = re.sub(r";; GENERATED by .*?;; END GENERATED\n", lambda m: gen, t, flags=re.S)
open(src, 'w').write(t)
print(len(names), 'ops in', len(groups), 'groups')
